stages:
  - stage: deploy
    jobs:
      - deployment: deploy_terraform
        continueOnError: false
        environment: 'dev'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - task: TerraformInstaller@0
                  displayName: 'install'
                  inputs:
                    terraformVersion: '1.1.0'
                - task: TerraformTaskV2@2
                  displayName: 'init'
                  inputs:
                    provider: 'aws'
                    command: 'init'
                    backendServiceAWS: 'ADOuser'
                    backendAWSBucketName: 'azuredevops22072022'
                    backendAWSKey: 'transit.tfstate'
                - task: TerraformTaskV2@2
                  displayName: 'apply'
                  inputs:
                    provider: 'aws'
                    command: 'apply'
                    environmentServiceNameAWS: 'ADOuser'
                    commandOptions: -input=false -var "ctrl_password=$(TF_VAR_ctrlpassword)" -var "ctrl_ip=$(TF_VAR_ctrlip)"